apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kse.fullname" . }}-streams
  labels:
    {{- include "kse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.streams.replicas }}
  selector:
    matchLabels:
      {{- include "kse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.streams.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kse.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.streams.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-streams
          image: '{{ include "kse.image" .Values.streams.image }}'
          imagePullPolicy: IfNotPresent
          env:  # 전달할 환경변수
            - name: KAFKA_BROKER
              value: {{ .Values.streams.kafka.server }}

          resources:
            {{- toYaml .Values.streams.resources | nindent 12 }}
      {{- with .Values.streams.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.streams.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.streams.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        - name: streams-waits-kafka
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          command: 
            - bash 
            - -c 
            - |
              # wait for kafka broker and source topic to be ready
              sleep 10
              while true; do
                EXISTING_TOPICS=$(kafka-topics.sh --bootstrap-server {{ .Values.streams.kafka.server }} --list 2> /dev/null)
                if [ $? -ne 0 ]; then
                  echo "Kafka broker not ready. retrying..."
                  sleep 5
                else
                  echo "Kafka broker Ready"
                  break
                fi

              done

